# Copyright (c) 2022, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

title: "Create a Private Endpoint from Resource Manager and do Remote-Exec in Private Instance"
stackDescription: ${Messages.solutionsHub.solutions.resourcemanagerCreatePrivateEndpoint.stackDescription()}
schemaVersion: 1.1.0
version: 1.0
locale: "en"


variableGroups:
- title: ${Messages.solutionsHub.generalConfig()}
  visible: false
  variables:
    - compartment_ocid
    - tenancy_ocid
    - region

- title: ${Messages.solutionsHub.optionalConfig()}
  visible: true  
  variables:
    - vcn_cidr
    - vcn_display_name
    - subnet_display_name
    - availability_domain_name
    - private_endpoint_display_name
    - instance_display_name
    - instance_shape
    - instance_os
    - instance_ocpus
    - instance_shape_config_memory_in_gbs

variables:

  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: ${Messages.solutionsHub.genericVariables.compartment.title()}
    description: ${Messages.solutionsHub.genericVariables.compartment.description()}

  region:
    type: oci:identity:region:name
    required: true
    title: ${Messages.solutionsHub.genericVariables.region.title()}
    description: ${Messages.solutionsHub.genericVariables.region.description()}

  availability_domain_name:
    type: oci:identity:availabilitydomain:name
    dependsOn:
      compartmentId: compartment_ocid
    required: true
    title: ${Messages.solutionsHub.genericVariables.availability_domain_name.title()}
    description: ${Messages.solutionsHub.genericVariables.availability_domain_name.description()}
    default: "tabw:PHX-AD-2"

  vcn_display_name:
    type: string
    required: true
    title: ${Messages.solutionsHub.solutions.resourcemanagerCreatePrivateEndpoint.variables.vcn_display_name.title()}
    description: ${Messages.solutionsHub.solutions.resourcemanagerCreatePrivateEndpoint.variables.vcn_display_name.description()}

  subnet_display_name:
    type: string
    required: true
    title: ${Messages.solutionsHub.solutions.resourcemanagerCreatePrivateEndpoint.variables.subnet_display_name.title()}
    description: ${Messages.solutionsHub.solutions.resourcemanagerCreatePrivateEndpoint.variables.subnet_display_name.description()}

  instance_display_name:
    type: string
    required: true
    title: ${Messages.solutionsHub.solutions.resourcemanagerCreatePrivateEndpoint.variables.instance_display_name.title()}
    description: ${Messages.solutionsHub.solutions.resourcemanagerCreatePrivateEndpoint.variables.instance_display_name.description()}

  private_endpoint_display_name:
    type: string
    required: true
    title: ${Messages.solutionsHub.solutions.resourcemanagerCreatePrivateEndpoint.variables.private_endpoint_display_name.title()}
    description: ${Messages.solutionsHub.solutions.resourcemanagerCreatePrivateEndpoint.variables.private_endpoint_display_name.description()}

  vcn_cidr:
    type: string
    required: false
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: ${Messages.solutionsHub.solutions.resourcemanagerCreatePrivateEndpoint.variables.vcn_cidr.title()}
    description: ${Messages.solutionsHub.solutions.resourcemanagerCreatePrivateEndpoint.variables.vcn_cidr.description()}

  instance_shape:
    type: oci:core:instanceshape:name
    required: false
    title: ${Messages.solutionsHub.solutions.resourcemanagerCreatePrivateEndpoint.variables.instance_shape.title()}
    description: ${Messages.solutionsHub.solutions.resourcemanagerCreatePrivateEndpoint.variables.instance_shape.description()}
    default: "VM.Standard.E3.Flex"
    dependsOn:
      compartmentId: compartment_ocid

  instance_os:
    type: enum
    title: ${Messages.solutionsHub.solutions.resourcemanagerCreatePrivateEndpoint.variables.instance_os.title()}
    description: ${Messages.solutionsHub.solutions.resourcemanagerCreatePrivateEndpoint.variables.instance_os.description()}
    enum:
      - "Oracle Linux"
    required: false

  instance_ocpus:
    type: integer
    minimum: 1
    maximum: 64
    title: ${Messages.solutionsHub.solutions.resourcemanagerCreatePrivateEndpoint.variables.instance_ocpus.title()}
    description: ${Messages.solutionsHub.solutions.resourcemanagerCreatePrivateEndpoint.variables.instance_ocpus.description()}
    visible:
      and:
        - not:
          - use_only_always_free_eligible_resources
        - or:
          - eq:
            - instance_shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - instance_shape 
            - "VM.Standard.E4.Flex"

  instance_shape_config_memory_in_gbs:
    type: integer
    minimum: 1
    maximum: 1024
    title: ${Messages.solutionsHub.solutions.resourcemanagerCreatePrivateEndpoint.variables.instance_shape_config_memory_in_gbs.title()}
    description: ${Messages.solutionsHub.solutions.resourcemanagerCreatePrivateEndpoint.variables.instance_shape_config_memory_in_gbs.description()}
    visible:
      and:
        - not:
          - use_only_always_free_eligible_resources
        - or:
          - eq:
            - instance_shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - instance_shape 
            - "VM.Standard.E4.Flex"
